(function(AdminApp) {

const GRACE_DAYS = 30;
const SEVERE_OVERDUE_DAYS = 60;
const MS_PER_DAY = 86400000;

const PAYMENT_STATUS_OPTIONS = ['Unpaid', 'Partial', 'Paid'];
const PAYMENT_STATUS_AUTO_OPTIONS = ['Auto', 'Unpaid', 'Partial', 'Paid'];
const CONTRACT_STATUS_OPTIONS = ['Pending', 'Active', 'Ended', 'Suspended'];
const PROPERTY_STATUS_OPTIONS = ['Vacant', 'Occupied', 'Rented', 'Under Renovation'];
const DEPOSIT_STATUS_OPTIONS = ['Pending', 'Paid', 'Returned', 'Official body'];
const ISSUE_STATUS_OPTIONS = ['Open', 'In Progress', 'Resolved', 'Closed'];
const PRIORITY_OPTIONS = ['High', 'Medium', 'Low'];
const EXPENSE_CATEGORY_OPTIONS = ['Council Tax', 'Insurance', 'Waste', 'Service Charge', 'Repairs', 'Utilities', 'Management', 'Legal', 'Tax', 'Other'];
const INVOICE_EXPENSE_CATEGORY_OPTIONS = ['Council Tax', 'Service Charge', 'Insurance', 'Maintenance', 'Utilities', 'Mortgage', 'Tax', 'Other'];
const DOCUMENT_TYPE_OPTIONS = ['Invoice', 'Transfer', 'Receipt'];
const PAYMENT_METHOD_OPTIONS = ['', 'transfer', 'bank transfer', 'cash', 'direct debit'];
const CONTACT_TYPE_OPTIONS = ['individual', 'company', 'government'];
const LEAD_STATUS_OPTIONS = ['New', 'Contacted', 'Qualified', 'Viewing', 'Negotiation', 'Won', 'Lost', 'Archived'];
const LEAD_INTEREST_OPTIONS = ['rental', 'purchase', 'investment', 'other'];
const LEAD_SOURCE_OPTIONS = ['direct', 'web', 'referral', 'portal', 'phone', 'email', 'other'];
const BATCH_STATUS_OPTIONS = ['Pending', 'Sent', 'Completed', 'Returned'];
const CONTACT_ASYNC_SELECT = { type: 'asyncSelect', asyncOptions: '/contacts/names', optionValue: 'name', optionLabel: 'name' };

const ENTITY_CONFIGS = {

    properties: {
        title: 'Property',
        entity: 'property',
        apiPath: '/properties',
        exportPath: '/export/properties',
        detailEntity: 'property',
        historyEntity: 'property',
        columns: [
            { key: 'thumbnail_url', label: 'Photo', type: 'thumbnail' },
            { key: 'property_name', label: 'Name' },
            { key: 'address', label: 'Address' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'contract_ref', label: 'Contract' },
            { key: 'rent', label: 'Rent', type: 'currency' },
            { key: 'start_date', label: 'Start', type: 'date' },
            { key: 'end_date', label: 'End', type: 'date' },
            { key: 'tags', label: 'Tags', type: 'tags' },
        ],
        filters: [
            { key: 'status', label: 'Status', options: PROPERTY_STATUS_OPTIONS },
        ],
        formFields: [
            { key: 'property_name', label: 'Property name', required: true, placeholder: 'e.g. 14 King Street Flat 3B' },
            { key: 'address', label: 'Address', required: true, placeholder: 'Full address' },
            { key: 'contract_ref', label: 'Contract ref', placeholder: 'Contract reference' },
            { key: 'status', label: 'Status', type: 'select', options: PROPERTY_STATUS_OPTIONS, default: 'Vacant' },
            { key: 'rent', label: 'Monthly rent', type: 'number', placeholder: '0.00' },
            { key: 'start_date', label: 'Contract start', type: 'date' },
            { key: 'end_date', label: 'Contract end', type: 'date' },
            { key: 'tags', label: 'Tags (comma separated)', placeholder: 'tag1, tag2' },
            { key: 'image_folder', label: 'Image folder', placeholder: 'e.g. 42 Royal Crescent' },
        ],
        tableOptions: { showCheckboxes: true },
        deleteConfirm: (row) => `Delete "${row.property_name}"? This action cannot be undone.`,
    },

    contracts: {
        title: 'Contract',
        entity: 'contract',
        apiPath: '/contracts',
        detailEntity: 'contract',
        historyEntity: 'contracts',
        columns: [
            { key: 'contract_ref', label: 'Contract' },
            { key: 'property_name', label: 'Property' },
            { key: 'tenant_name', label: 'Tenant' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'rent', label: 'Rent', type: 'currency' },
            { key: 'start_date', label: 'Start', type: 'date' },
            { key: 'end_date', label: 'End', type: 'date' },
            { key: 'doc_count', label: 'Docs', type: 'badge_count', suffix: 'docs' },
            { key: 'tags', label: 'Tags', type: 'tags' },
        ],
        filters: [
            { key: 'status', label: 'Status', options: CONTRACT_STATUS_OPTIONS },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
            { key: 'tenant_name', label: 'Tenant', asyncOptions: '/tenants/names' },
        ],
        formFields: [
            { key: 'contract_ref', label: 'Contract ref', required: true, placeholder: 'e.g. 14 KING ST - JOHNSON' },
            { key: 'property_name', label: 'Property', required: true, placeholder: 'Property name' },
            { key: 'address', label: 'Address', placeholder: 'Full address' },
            { key: 'tenant_name', label: 'Tenant', placeholder: 'Tenant name' },
            { key: 'status', label: 'Status', type: 'select', options: CONTRACT_STATUS_OPTIONS, default: 'Pending' },
            { key: 'rent', label: 'Monthly rent', type: 'number', placeholder: '0.00' },
            { key: 'total_value', label: 'Total contract value', type: 'number', placeholder: '0.00' },
            { key: 'start_date', label: 'Start date', type: 'date' },
            { key: 'end_date', label: 'End date', type: 'date' },
            { key: 'tags', label: 'Tags (comma separated)', placeholder: 'tag1, tag2' },
        ],
        tableOptions: {},
        deleteConfirm: (row) => `Delete "${row.contract_ref}"? This action cannot be undone.`,
    },

    rentals: {
        title: 'Rental',
        entity: 'rentals',
        apiPath: '/invoices',
        exportPath: '/export/invoices',
        detailEntity: 'invoice',
        historyEntity: 'invoices',
        columns: [
            { key: 'invoice_number', label: 'Inv.#' },
            { key: 'invoice_date', label: 'Date', type: 'date' },
            { key: 'property_name', label: 'Property', type: 'multiline', subKey: 'property_address' },
            { key: 'contract_ref', label: 'Contract', type: 'multiline', subKey: 'contract_parties' },
            { key: 'amount', label: 'Net', type: 'currency' },
            { key: 'vat', label: 'Tax', type: 'currency' },
            { key: 'retention', label: 'Retention', type: 'currency' },
            { key: 'total', label: 'Total', type: 'currency' },
            { key: 'paid', label: 'Paid', type: 'currency' },
            { key: 'status', label: 'Status', type: 'status' },
        ],
        filters: [
            { key: 'status', label: 'Status', options: PAYMENT_STATUS_OPTIONS },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'document_type', label: 'Document type', type: 'select', options: DOCUMENT_TYPE_OPTIONS, default: 'Receipt' },
            { key: 'reference', label: 'Reference', required: true, placeholder: 'ALQ-2026-001' },
            { key: 'invoice_number', label: 'Invoice no.', type: 'number', placeholder: 'Auto if empty' },
            { key: 'description', label: 'Description', required: true, placeholder: 'Monthly rent' },
            { key: 'contract_ref', label: 'Contract', required: true, placeholder: 'Contract reference' },
            { key: 'property_name', label: 'Property', required: true, placeholder: 'Property name' },
            { key: 'payer', label: 'Payer', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'payee', label: 'Payee', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'status', label: 'Status', type: 'select', options: PAYMENT_STATUS_AUTO_OPTIONS, default: 'Auto' },
            { key: 'amount', label: 'Net', type: 'number', required: true, placeholder: '0.00' },
            { key: 'vat', label: 'Tax/VAT', type: 'number', placeholder: '0.00' },
            { key: 'retention', label: 'Retention', type: 'number', placeholder: '0.00' },
            { key: 'total', label: 'Total', type: 'number', required: true, placeholder: '0.00' },
            { key: 'paid', label: 'Paid', type: 'number', placeholder: '0.00' },
            { key: 'invoice_date', label: 'Invoice date', required: true, placeholder: 'YYYY-MM-DD' },
            { key: 'payment_date', label: 'Payment date', type: 'date' },
            { key: 'payment_method', label: 'Payment method', type: 'select', options: PAYMENT_METHOD_OPTIONS },
            { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional notes...' },
            { key: 'payer_account', label: 'Payer account', placeholder: 'IBAN' },
        ],
        tableOptions: {
            showPeriodFilter: true,
            showCheckboxes: true,
            defaultFilters: { type: 'income' },
            hasPdf: true,
        },
        hiddenFields: { type: 'income' },
        onSubmitTransform: (data) => { if (data.status === 'Auto') delete data.status; return data; },
        deleteConfirm: (row) => `Delete "${row.reference}"? This action cannot be undone.`,
    },

    billing: {
        title: 'Invoice',
        entity: 'billing',
        apiPath: '/invoices',
        exportPath: '/export/invoices',
        detailEntity: 'invoice',
        historyEntity: 'invoices',
        columns: [
            { key: 'invoice_number', label: 'Inv.#' },
            { key: 'document_type', label: 'Type' },
            { key: 'reference', label: 'Reference' },
            { key: 'description', label: 'Description' },
            { key: 'property_name', label: 'Property' },
            { key: 'payer', label: 'Payer' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'total', label: 'Total', type: 'currency' },
            { key: 'paid', label: 'Paid', type: 'currency' },
            { key: 'invoice_date', label: 'Date', type: 'date' },
            { key: 'collection_date', label: 'Coll. date', type: 'date' },
        ],
        filters: [
            { key: 'document_type', label: 'Type', options: DOCUMENT_TYPE_OPTIONS },
            { key: 'status', label: 'Status', options: PAYMENT_STATUS_OPTIONS },
            { key: 'owner_id', label: 'Owner', asyncOptions: '/invoices/owners', optionValue: 'id', optionLabel: 'name' },
            { key: 'payee_id', label: 'Payee', asyncOptions: '/contacts/names', optionValue: 'id', optionLabel: 'name' },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'document_type', label: 'Document type', type: 'select', options: DOCUMENT_TYPE_OPTIONS, default: 'Invoice' },
            { key: 'reference', label: 'Reference', required: true, placeholder: 'INV-2026-001' },
            { key: 'invoice_number', label: 'Invoice no.', type: 'number', placeholder: 'Auto if empty' },
            { key: 'description', label: 'Description', required: true, placeholder: 'Invoice description' },
            { key: 'contract_ref', label: 'Contract', required: true, placeholder: 'Contract reference' },
            { key: 'property_name', label: 'Property', required: true, placeholder: 'Property name' },
            { key: 'payer', label: 'Payer', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'payee', label: 'Payee', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'status', label: 'Status', type: 'select', options: PAYMENT_STATUS_AUTO_OPTIONS, default: 'Auto' },
            { key: 'amount', label: 'Net', type: 'number', placeholder: '0.00' },
            { key: 'vat', label: 'VAT', type: 'number', placeholder: '0.00' },
            { key: 'retention', label: 'Retention', type: 'number', placeholder: '0.00' },
            { key: 'total', label: 'Total', type: 'number', required: true, placeholder: '0.00' },
            { key: 'paid', label: 'Paid', type: 'number', placeholder: '0.00' },
            { key: 'invoice_date', label: 'Invoice date', required: true, placeholder: 'YYYY-MM-DD' },
            { key: 'payment_date', label: 'Payment date', type: 'date' },
            { key: 'collection_date', label: 'Collection date', type: 'date' },
            { key: 'payment_method', label: 'Payment method', type: 'select', options: PAYMENT_METHOD_OPTIONS },
            { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional notes...' },
            { key: 'discount', label: 'Discount', type: 'number', placeholder: '0.00' },
            { key: 'discount_pct', label: 'Discount %', type: 'number', placeholder: '0.00' },
            { key: 'payer_account', label: 'Payer account', placeholder: 'IBAN' },
        ],
        tableOptions: {
            showPeriodFilter: true,
            showCheckboxes: true,
            defaultFilters: { type: 'income' },
            hasPdf: true,
        },
        hiddenFields: { type: 'income' },
        onSubmitTransform: (data) => { if (data.status === 'Auto') delete data.status; return data; },
        deleteConfirm: (row) => `Delete "${row.reference}"? This action cannot be undone.`,
    },

    expenses: {
        title: 'Expense',
        entity: 'expenses',
        apiPath: '/invoices',
        exportPath: '/export/invoices',
        detailEntity: 'invoice',
        historyEntity: 'invoices',
        columns: [
            { key: 'invoice_number', label: 'Inv.#' },
            { key: 'reference', label: 'Reference' },
            { key: 'description', label: 'Description' },
            { key: 'property_name', label: 'Property' },
            { key: 'expense_category', label: 'Category' },
            { key: 'payee', label: 'Supplier' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'total', label: 'Total', type: 'currency' },
            { key: 'paid', label: 'Paid', type: 'currency' },
            { key: 'invoice_date', label: 'Date', type: 'date' },
        ],
        filters: [
            { key: 'expense_category', label: 'Category', options: EXPENSE_CATEGORY_OPTIONS },
            { key: 'status', label: 'Status', options: PAYMENT_STATUS_OPTIONS },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'reference', label: 'Reference', required: true, placeholder: 'EXP-2026-001' },
            { key: 'invoice_number', label: 'Invoice no.', type: 'number', placeholder: 'Auto if empty' },
            { key: 'description', label: 'Description', required: true, placeholder: 'Expense description' },
            { key: 'property_name', label: 'Property', required: true, placeholder: 'Property name' },
            { key: 'expense_category', label: 'Category', type: 'select', options: EXPENSE_CATEGORY_OPTIONS, default: 'Other' },
            { key: 'payer', label: 'Payer', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'payee', label: 'Payee', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'contract_ref', label: 'Contract', placeholder: 'Contract reference (optional)' },
            { key: 'status', label: 'Status', type: 'select', options: PAYMENT_STATUS_AUTO_OPTIONS, default: 'Auto' },
            { key: 'total', label: 'Total', type: 'number', required: true, placeholder: '0.00' },
            { key: 'paid', label: 'Paid', type: 'number', placeholder: '0.00' },
            { key: 'vat', label: 'VAT', type: 'number', placeholder: '0.00' },
            { key: 'invoice_date', label: 'Date', required: true, placeholder: 'YYYY-MM-DD' },
            { key: 'payment_date', label: 'Payment date', type: 'date' },
            { key: 'payment_method', label: 'Payment method', type: 'select', options: PAYMENT_METHOD_OPTIONS },
            { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional notes...' },
        ],
        tableOptions: {
            showPeriodFilter: true,
            defaultFilters: { type: 'expense' },
            hasPdf: true,
        },
        hiddenFields: { type: 'expense' },
        onSubmitTransform: (data) => { if (data.status === 'Auto') delete data.status; return data; },
        deleteConfirm: (row) => `Delete "${row.reference}"? This action cannot be undone.`,
    },

    invoices: {
        title: 'Invoice',
        entity: 'invoices',
        apiPath: '/invoices',
        exportPath: '/export/invoices',
        detailEntity: 'invoice',
        historyEntity: 'invoices',
        columns: [
            { key: 'invoice_number', label: 'Inv.#' },
            { key: 'reference', label: 'Reference' },
            { key: 'description', label: 'Description' },
            { key: 'property_name', label: 'Property' },
            { key: 'payer', label: 'Payer' },
            { key: 'payee', label: 'Payee' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'total', label: 'Total', type: 'currency' },
            { key: 'paid', label: 'Paid', type: 'currency' },
            { key: 'type', label: 'Type', type: 'status' },
            { key: 'expense_category', label: 'Category' },
            { key: 'invoice_date', label: 'Date', type: 'date' },
        ],
        filters: [
            { key: 'status', label: 'Status', options: PAYMENT_STATUS_OPTIONS },
            { key: 'type', label: 'Type', options: ['income', 'expense'] },
            { key: 'expense_category', label: 'Category', options: INVOICE_EXPENSE_CATEGORY_OPTIONS },
            { key: 'payee_id', label: 'Payee', asyncOptions: '/contacts/names', optionValue: 'id', optionLabel: 'name' },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'document_type', label: 'Document type', type: 'select', options: DOCUMENT_TYPE_OPTIONS, default: 'Invoice' },
            { key: 'reference', label: 'Reference', required: true, placeholder: 'INV-2026-001' },
            { key: 'invoice_number', label: 'Invoice no.', type: 'number', placeholder: 'Auto if empty' },
            { key: 'description', label: 'Description', required: true, placeholder: 'Invoice description' },
            { key: 'contract_ref', label: 'Contract', required: true, placeholder: 'Contract reference' },
            { key: 'property_name', label: 'Property', required: true, placeholder: 'Property name' },
            { key: 'payer', label: 'Payer', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'payee', label: 'Payee', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'status', label: 'Status', type: 'select', options: PAYMENT_STATUS_AUTO_OPTIONS, default: 'Auto' },
            { key: 'type', label: 'Type', type: 'select', options: ['income', 'expense'], default: 'income' },
            { key: 'expense_category', label: 'Expense category', type: 'select', options: ['', ...INVOICE_EXPENSE_CATEGORY_OPTIONS] },
            { key: 'total', label: 'Total', type: 'number', required: true, placeholder: '0.00' },
            { key: 'paid', label: 'Paid', type: 'number', placeholder: '0.00' },
            { key: 'vat', label: 'VAT', type: 'number', placeholder: '0.00' },
            { key: 'invoice_date', label: 'Invoice date', required: true, placeholder: 'YYYY-MM-DD' },
            { key: 'payment_date', label: 'Payment date', type: 'date' },
            { key: 'payment_method', label: 'Payment method', type: 'select', options: PAYMENT_METHOD_OPTIONS },
            { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional notes...' },
            { key: 'discount', label: 'Discount', type: 'number', placeholder: '0.00' },
            { key: 'discount_pct', label: 'Discount %', type: 'number', placeholder: '0.00' },
            { key: 'payer_account', label: 'Payer account', placeholder: 'IBAN' },
        ],
        tableOptions: {
            showPeriodFilter: true,
            hasPdf: true,
        },
        onSubmitTransform: (data) => { if (data.status === 'Auto') delete data.status; return data; },
        deleteConfirm: (row) => `Delete "${row.reference}"? This action cannot be undone.`,
    },

    deposits: {
        title: 'Deposit',
        entity: 'deposit',
        apiPath: '/deposits',
        detailEntity: 'deposit',
        historyEntity: 'deposits',
        columns: [
            { key: 'deposit_date', label: 'Date', type: 'date' },
            { key: 'property_name', label: 'Property' },
            { key: 'payer', label: 'Payer' },
            { key: 'payee', label: 'Payee' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'amount', label: 'Amount', type: 'currency' },
            { key: 'is_owner', label: 'Owner', type: 'boolean', trueLabel: 'Owner' },
            { key: 'created_at', label: 'Created', type: 'date' },
        ],
        filters: [
            { key: 'status', label: 'Status', options: DEPOSIT_STATUS_OPTIONS },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'deposit_date', label: 'Date', type: 'date', required: true },
            { key: 'property_name', label: 'Property', required: true, placeholder: 'Property name' },
            { key: 'payer', label: 'Payer', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'payee', label: 'Payee', required: true, ...CONTACT_ASYNC_SELECT },
            { key: 'deposit_type', label: 'Type', required: true, placeholder: 'e.g. Bond' },
            { key: 'status', label: 'Status', type: 'select', required: true, options: DEPOSIT_STATUS_OPTIONS },
            { key: 'amount', label: 'Amount', type: 'number', required: true, placeholder: '0.00' },
            { key: 'payment_date', label: 'Payment date', type: 'date' },
            { key: 'refund_date', label: 'Refund date', type: 'date' },
            { key: 'contract_ref', label: 'Contract ref', placeholder: 'Contract reference' },
            { key: 'paid', label: 'Amount paid', type: 'number', placeholder: '0.00' },
            { key: 'refunded', label: 'Amount returned', type: 'number', placeholder: '0.00' },
            { key: 'is_owner', label: 'Owner deposit', type: 'select', options: ['false', 'true'], default: 'false' },
        ],
        tableOptions: {},
        deleteConfirm: (row) => `Delete deposit for "${row.property_name}"? This action cannot be undone.`,
    },

    sepa_batches: {
        title: 'SEPA Batch',
        entity: 'sepa_batches',
        apiPath: '/sepa-batches',
        detailEntity: 'sepa_batch',
        historyEntity: 'sepa_batches',
        columns: [
            { key: 'collection_date', label: 'Collection date', type: 'date' },
            { key: 'batch_name', label: 'Name' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'creditor', label: 'Creditor' },
            { key: 'total_records', label: 'Records' },
            { key: 'total_amount', label: 'Total', type: 'currency' },
            { key: 'created_at', label: 'Created', type: 'date' },
        ],
        filters: [
            { key: 'status', label: 'Status', options: BATCH_STATUS_OPTIONS },
            { key: 'creditor', label: 'Creditor', asyncOptions: '/sepa-batches/creditors' },
        ],
        formFields: [
            { key: 'batch_name', label: 'Batch name', required: true },
            { key: 'collection_date', label: 'Collection date', type: 'date', required: true },
            { key: 'status', label: 'Status', type: 'select', options: BATCH_STATUS_OPTIONS },
            { key: 'creditor', label: 'Creditor (name)', required: true },
            { key: 'creditor_id', label: 'Creditor ID' },
            { key: 'creditor_suffix', label: 'Suffix' },
            { key: 'debtor', label: 'Debtor (name)' },
            { key: 'debtor_iban', label: 'Debtor IBAN' },
            { key: 'debtor_swift_bic', label: 'Debtor SWIFT/BIC' },
            { key: 'debtor_creditor_id', label: 'Debtor Creditor ID' },
            { key: 'debtor_suffix', label: 'Debtor Suffix' },
            { key: 'notes', label: 'Notes', type: 'textarea' },
        ],
        tableOptions: {
            showPeriodFilter: true,
        },
        deleteConfirm: (row) => `Delete batch "${row.batch_name}"? Linked invoices will NOT be deleted.`,
    },

    issues: {
        title: 'Issue',
        entity: 'issue',
        apiPath: '/issues',
        exportPath: '/export/issues',
        detailEntity: 'issue',
        historyEntity: 'issues',
        columns: [
            { key: 'property_name', label: 'Property' },
            { key: 'title', label: 'Title' },
            { key: 'priority', label: 'Priority', type: 'status' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'cost', label: 'Cost', type: 'currency' },
            { key: 'created_at', label: 'Created', type: 'date' },
        ],
        filters: [
            { key: 'status', label: 'Status', options: ISSUE_STATUS_OPTIONS },
            { key: 'priority', label: 'Priority', options: PRIORITY_OPTIONS },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'property_name', label: 'Property', required: true, placeholder: 'Property name' },
            { key: 'title', label: 'Title', required: true, placeholder: 'Brief description of the issue' },
            { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Detailed description...' },
            { key: 'priority', label: 'Priority', type: 'select', options: PRIORITY_OPTIONS, default: 'Medium' },
            { key: 'status', label: 'Status', type: 'select', options: ISSUE_STATUS_OPTIONS, default: 'Open' },
            { key: 'cost', label: 'Cost', type: 'number', placeholder: '0.00' },
        ],
        tableOptions: {},
        deleteConfirm: (row) => `Delete "${row.title}"? This action cannot be undone.`,
    },

    tenants: {
        title: 'Tenant',
        entity: 'tenant',
        apiPath: '/tenants',
        detailEntity: 'tenant',
        historyEntity: 'tenants',
        columns: [
            { key: 'name', label: 'Name' },
            { key: 'tax_id', label: 'National ID' },
            { key: 'email', label: 'Email' },
            { key: 'phone', label: 'Phone' },
            { key: 'property_name', label: 'Property' },
            { key: 'created_at', label: 'Created', type: 'date' },
        ],
        filters: [
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'name', label: 'Full name', required: true, placeholder: 'Full name' },
            { key: 'tax_id', label: 'National ID', required: true, placeholder: 'ID number' },
            { key: 'email', label: 'Email', required: true, placeholder: 'email@example.com' },
            { key: 'phone', label: 'Phone', required: true, placeholder: '+44 7700 000 000' },
            { key: 'address', label: 'Address', placeholder: 'Current address' },
            { key: 'bank_account', label: 'Bank account (IBAN)', placeholder: 'GB00 0000 0000 0000 0000 00' },
            { key: 'property_name', label: 'Property', placeholder: 'Associated property' },
            { key: 'property_address', label: 'Property address', placeholder: 'Property address' },
            { key: 'is_legacy', label: 'Legacy tenant', type: 'select', options: ['false', 'true'], default: 'false' },
            { key: 'guarantor_name', label: 'Guarantor name', placeholder: 'Guarantor full name' },
            { key: 'guarantor_id', label: 'Guarantor ID', placeholder: 'Guarantor ID' },
            { key: 'guarantor_phone', label: 'Guarantor phone', placeholder: '+44 7700 000 000' },
            { key: 'guarantor_email', label: 'Guarantor email', placeholder: 'guarantor@example.com' },
        ],
        tableOptions: {},
        deleteConfirm: (row) => `Delete "${row.name}"? This action cannot be undone.`,
    },

    owners: {
        title: 'Owner',
        entity: 'owner',
        apiPath: '/owners',
        detailEntity: 'owner',
        historyEntity: 'owners',
        columns: [
            { key: 'name', label: 'Name' },
            { key: 'tax_id', label: 'Tax ID' },
            { key: 'email', label: 'Email' },
            { key: 'phone', label: 'Phone' },
            { key: 'property_name', label: 'Property' },
            { key: 'created_at', label: 'Created', type: 'date' },
        ],
        filters: [
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'name', label: 'Full name', required: true, placeholder: 'Full name' },
            { key: 'tax_id', label: 'Tax ID', required: true, placeholder: 'NI/UTR' },
            { key: 'email', label: 'Email', placeholder: 'email@example.com' },
            { key: 'phone', label: 'Phone', placeholder: '+44 7700 000 000' },
            { key: 'address', label: 'Address', placeholder: 'Current address' },
            { key: 'bank_account', label: 'Bank account', placeholder: 'Bank name or IBAN' },
            { key: 'property_name', label: 'Property', placeholder: 'Associated property' },
            { key: 'property_address', label: 'Property address', placeholder: 'Property address' },
        ],
        tableOptions: {},
        deleteConfirm: (row) => `Delete "${row.name}"? This action cannot be undone.`,
    },

    overdue: {
        title: 'Overdue',
        entity: 'overdue',
        apiPath: '/invoices',
        exportPath: '/export/invoices',
        detailEntity: 'invoice',
        columns: [
            { key: 'reference', label: 'Invoice #' },
            { key: 'description', label: 'Description', type: 'multiline', subKey: 'property_name' },
            { key: 'payer', label: 'Payer' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'total', label: 'Total', type: 'currency' },
            { key: 'paid', label: 'Paid', type: 'currency' },
            { key: '_outstanding', label: 'Pending', render: function(val, row) {
                const pending = parseFloat(row.total || 0) - parseFloat(row.paid || 0);
                if (pending <= 0) return AdminApp.formatCurrency(0);
                return '<span class="text-danger text-semibold">' + AdminApp.formatCurrency(pending) + '</span>';
            }},
            { key: 'invoice_date', label: 'Date', type: 'date' },
            { key: 'collection_date', label: 'Coll. date', type: 'date' },
            { key: '_overdue', label: 'Overdue', render: function(val, row) {
                const refDate = row.collection_date || row.invoice_date;
                if (!refDate) return '-';
                const elapsed = Math.floor((Date.now() - new Date(refDate).getTime()) / MS_PER_DAY);
                const overdueDays = elapsed - GRACE_DAYS;
                if (overdueDays > 0) {
                    const sev = overdueDays > SEVERE_OVERDUE_DAYS ? 'red' : 'amber';
                    return '<span class="badge badge-' + sev + '">' + overdueDays + 'd overdue</span>';
                }
                const remaining = GRACE_DAYS - elapsed;
                return '<span class="badge badge-gray">' + remaining + 'd remaining</span>';
            }},
        ],
        filters: [
            { key: 'status', label: 'Status', options: ['Unpaid', 'Partial'] },
            { key: 'owner_id', label: 'Owner', asyncOptions: '/invoices/owners', optionValue: 'id', optionLabel: 'name' },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        tableOptions: {
            showPeriodFilter: true,
            readOnly: true,
            defaultFilters: { type: 'income', status: 'Unpaid' },
        },
    },

    leads: {
        title: 'Lead',
        entity: 'lead',
        apiPath: '/leads',
        detailEntity: 'lead',
        historyEntity: 'leads',
        columns: [
            { key: 'name', label: 'Name' },
            { key: 'email', label: 'Email' },
            { key: 'phone', label: 'Phone' },
            { key: 'status', label: 'Status', type: 'status' },
            { key: 'interest_type', label: 'Interest', type: 'status' },
            { key: 'property_name', label: 'Property' },
            { key: 'source', label: 'Source' },
            { key: 'follow_up_date', label: 'Follow-up', type: 'date' },
            { key: 'score', label: 'Score' },
            { key: 'created_at', label: 'Created', type: 'date' },
        ],
        filters: [
            { key: 'status', label: 'Status', options: LEAD_STATUS_OPTIONS },
            { key: 'interest_type', label: 'Interest', options: LEAD_INTEREST_OPTIONS },
            { key: 'source', label: 'Source', options: LEAD_SOURCE_OPTIONS },
            { key: 'property_name', label: 'Property', asyncOptions: '/properties/names' },
        ],
        formFields: [
            { key: 'name', label: 'Name', required: true, placeholder: 'Contact name' },
            { key: 'email', label: 'Email', placeholder: 'email@example.com' },
            { key: 'phone', label: 'Phone', placeholder: '+44 7700 000 000' },
            { key: 'company', label: 'Company', placeholder: 'Company name' },
            { key: 'source', label: 'Source', type: 'select', options: LEAD_SOURCE_OPTIONS, default: 'direct' },
            { key: 'status', label: 'Status', type: 'select', options: LEAD_STATUS_OPTIONS, default: 'New' },
            { key: 'interest_type', label: 'Interest', type: 'select', options: LEAD_INTEREST_OPTIONS, default: 'rental' },
            { key: 'property_name', label: 'Property of interest', type: 'asyncSelect', asyncOptions: '/properties/names' },
            { key: 'budget_min', label: 'Min budget (GBP)', type: 'number', placeholder: '0' },
            { key: 'budget_max', label: 'Max budget (GBP)', type: 'number', placeholder: '0' },
            { key: 'min_bedrooms', label: 'Min bedrooms', type: 'number', placeholder: '0' },
            { key: 'min_sqm', label: 'Min sq ft', type: 'number', placeholder: '0' },
            { key: 'preferred_area', label: 'Preferred area', placeholder: 'Area, city...' },
            { key: 'follow_up_date', label: 'Next follow-up', type: 'date' },
            { key: 'assigned_to', label: 'Assigned to', placeholder: 'Assigned agent' },
            { key: 'score', label: 'Score (0-100)', type: 'number', placeholder: '0' },
            { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'General notes...' },
        ],
        tableOptions: {},
        deleteConfirm: (row) => `Delete "${row.name}"? This action cannot be undone.`,
    },

    contacts: {
        title: 'Contact',
        entity: 'contact',
        apiPath: '/contacts',
        detailEntity: null,
        historyEntity: 'contacts',
        columns: [
            { key: 'name', label: 'Name' },
            { key: 'tax_id', label: 'Tax ID' },
            { key: 'iban', label: 'IBAN' },
            { key: 'email', label: 'Email' },
            { key: 'phone', label: 'Phone' },
            { key: 'contact_type', label: 'Type' },
            { key: 'created_at', label: 'Created', type: 'date' },
        ],
        filters: [
            { key: 'contact_type', label: 'Type', options: CONTACT_TYPE_OPTIONS },
        ],
        formFields: [
            { key: 'name', label: 'Name', required: true, placeholder: 'Full name or company name' },
            { key: 'tax_id', label: 'Tax ID', placeholder: 'Tax ID' },
            { key: 'iban', label: 'IBAN', placeholder: 'GB00 0000 0000 0000 0000 00' },
            { key: 'email', label: 'Email', placeholder: 'email@example.com' },
            { key: 'phone', label: 'Phone', placeholder: '+44 7700 000 000' },
            { key: 'address', label: 'Address', placeholder: 'Full address' },
            { key: 'contact_type', label: 'Type', type: 'select', options: CONTACT_TYPE_OPTIONS },
            { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional notes...' },
        ],
        tableOptions: {},
        deleteConfirm: (row) => `Delete "${row.name}"? This action cannot be undone.`,
    },

};

Object.assign(AdminApp, { ENTITY_CONFIGS });

})(window.AdminApp);
